ALTER TABLE Businesses
DROP COLUMN mission;

ALTER TABLE Businesses
DROP COLUMN v;

ALTER TABLE Businesses
ADD COLUMN aboutUs varchar(1200);

INSERT INTO `braganza`.`Businesses`
(`id`,
`name`,
`address`,
`aboutUs`,
`logo`,
`status`,
`createdAt`,
`updatedAt`)
VALUES
(1,
'Branganza Vial', 
'Uruguay',
'BRAGANZA VIAL SAS ES UNA EMPRESA ESPECIALIZADA EN LA REALIZACIÓN DE OBRAS DE INFRAESTRUCTURA, FUNDADA POR EDUARDO JOAO, CON MÁS DE 15 AÑOS DE EXPERIENCIA EN EL RUBRO.
ESTÁ COMPUESTA POR UN JOVEN EQUIPO QUE CUENTA CON AMPLIA EXPERIENCIA, Y DISPONE DE UN EXTENSO PARQUE DE MAQUINARIA QUE PERMITAN LA REALIZACIÓN DE LOS TRABAJOS DE UNA MANERA SEGURA Y EFICIENTE.
CADA PROYECTO PARA NOSOTROS REPRESENTA UN RETO QUE ESTAMOS DISPUESTOS A AFRONTAR CON DEDICACIÓN, SIEMPRE MOSTRANDO NUESTRO COMPROMISO EN CUMPLIR CON LAS EXPECTATIVAS DE NUESTROS CLIENTES. NOS ENFOCAMOS EN BRINDAR LAS MEJORES SOLUCIONES CONSTRUCTIVAS EN BASE A LAS NECESIDADES PARTICULARES, CARACTERIZÁNDONOS POR NUESTRA FLEXIBILIDAD ANTE CUALQUIER TRABAJO, APOSTANDO SIEMPRE AL ÉXITO DEL PROYECTO, EN CUANTO A TIEMPOS DE CONSTRUCCIÓN Y CALIDAD.',
'logo',
'a',
'2023-03-16 16:15:39',
'2023-03-16 16:15:39');

INSERT INTO `braganza`.`Roles`
(`id`,
`name`,
`status`,
`createdAt`,
`updatedAt`)
VALUES
(1,
'Superadmin',
'a',
'2023-03-16 16:48:23',
'2023-03-16 16:48:23'),
(2,
'Admin',
'a',
'2023-03-16 16:48:23',
'2023-03-16 16:48:23'),
(3,
'Customer',
'a',
'2023-03-16 16:48:23',
'2023-03-16 16:48:23');